version: '3'

tasks:
  build:
    cmds:
      - odin build src/ -out:target/json -error-pos-style:unix -o:none -ignore-unknown-attributes 
    sources:
      - ./src/**/*.odin
    generates:
    - target/json
    silent: true
  
  run:
    cmds:
      - ./target/json test
    deps: 
      - build
    silent: true
  

interval: 250ms