version: '3'

tasks:
  build:
    cmds:
      - odin build src/ -out:target/json -error-pos-style:unix -o:none -debug -ignore-unknown-attributes 
    sources:
      - ./src/**/*.odin
    generates:
    - target/json
    silent: true
  
  run:
    cmds:
      - ./target/json test_dir
    deps: 
      - build
    silent: true

  test:
    cmds:
      - ./target/json test
      - odin test test  -o:none -debug -ignore-unknown-attributes
    sources:
      - ./src/**/*.odin
    deps:
      - build
  

interval: 250ms